// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5FqVBEMLgleHddleZWY4qO28N3ePijHc',
    appId: '1:184925199163:web:c077c8b493ee7faeed351e',
    messagingSenderId: '184925199163',
    projectId: 'hack-it-79e99',
    authDomain: 'hack-it-79e99.firebaseapp.com',
    storageBucket: 'hack-it-79e99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgHOCHpkFWCZaKI_xy_ehL2U_w4otYPGs',
    appId: '1:184925199163:android:ee20cb5a387847dced351e',
    messagingSenderId: '184925199163',
    projectId: 'hack-it-79e99',
    storageBucket: 'hack-it-79e99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd23d9ZT8JmrUqpaYZwy0So5pmsXJkDtk',
    appId: '1:184925199163:ios:43a58e07bb4acb05ed351e',
    messagingSenderId: '184925199163',
    projectId: 'hack-it-79e99',
    storageBucket: 'hack-it-79e99.appspot.com',
    iosClientId: '184925199163-reul5e54q0d26mvfguh99hngqe6qf8am.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd23d9ZT8JmrUqpaYZwy0So5pmsXJkDtk',
    appId: '1:184925199163:ios:43a58e07bb4acb05ed351e',
    messagingSenderId: '184925199163',
    projectId: 'hack-it-79e99',
    storageBucket: 'hack-it-79e99.appspot.com',
    iosClientId: '184925199163-reul5e54q0d26mvfguh99hngqe6qf8am.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackIt',
  );
}
